trigger:
  branches:
    include:
      - "*"  # Dispara a pipeline em qualquer branch

pr:
  branches:
    include:
      - "*"  # Dispara a pipeline em qualquer PR

variables:
  dotnetVersion: '8.x'
  publishDirectory: $(Build.ArtifactStagingDirectory)/publish
  imageName: $(DOCKER_USERNAME)/$(DOCKER_REPO):latest

jobs:
- job: Build
  displayName: 'Build and Publish'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: $(dotnetVersion)

  - script: dotnet restore
    displayName: 'Restore dependencies'

  - script: dotnet build --no-restore --configuration Release
    displayName: 'Build the project'

  - script: dotnet test --no-build --verbosity normal --configuration Release
    displayName: 'Run tests'

  - script: |
      dotnet publish Geempe/Geempe.Api.csproj --no-build --configuration Release --output $(publishDirectory)/api
      dotnet publish Geempe.Application/Geempe.Application.csproj --no-build --configuration Release --output $(publishDirectory)/application
      dotnet publish Geempe.Domain/Geempe.Domain.csproj --no-build --configuration Release --output $(publishDirectory)/domain
      dotnet publish Geempe.IoC/Geempe.IoC.csproj --no-build --configuration Release --output $(publishDirectory)/ioc
      dotnet publish Geempe.Infra/Geempe.Infra.csproj --no-build --configuration Release --output $(publishDirectory)/infra
    displayName: 'Publish projects'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(publishDirectory)
      ArtifactName: 'published-artifacts'
      publishLocation: 'Container'



