name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x' 

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --verbosity normal --configuration Release

      - name: Publish artifacts
        if: success()
        run: dotnet publish --no-build --configuration Release --output ./publish

      - name: Build Docker image
        run: docker build -t LuisFernandoFernandes/geempe-api:${{ github.sha }} -f Geempe/Geempe/Dockerfile .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push LuisFernandoFernandes/geempe-api:${{ github.sha }}

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull LuisFernandoFernandes/geempe-api:${{ github.sha }}
            docker stop geempe-api || true
            docker rm geempe-api || true
            docker run -d --name geempe-api -p 80:80 LuisFernandoFernandes/geempe-api:${{ github.sha }}
