name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x' 

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --verbosity normal --configuration Release

      - name: Publish API
        run: dotnet publish Geempe.Api/Geempe.Api.csproj --no-build --configuration Release --output ./publish/api

      - name: Publish Application
        run: dotnet publish Geempe.Application/Geempe.Application.csproj --no-build --configuration Release --output ./publish/application
      
      - name: Publish Domain
        run: dotnet publish Geempe.Domain/Geempe.Domain.csproj --no-build --configuration Release --output ./publish/domain

      - name: Publish IoC
        run: dotnet publish Geempe.IoC/Geempe.IoC.csproj --no-build --configuration Release --output ./publish/ioc
        
      - name: Publish Infra
        run: dotnet publish Geempe.Infra/Geempe.Infra.csproj --no-build --configuration Release --output ./publish/infra
