name: Deploy 

on:
  push:
    branches: [ "prod" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x' 

      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t geempe-api:${{ github.sha }} -f Geempe/Dockerfile .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Tag Docker Image
        run: docker tag geempe-api:latest ${{ secrets.DOCKER_USERNAME }}/geempe-api:${{ github.sha }}
      
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/geempe-api:${{ github.sha }}

   #   - name: Deploy to server
    #    uses: appleboy/ssh-action@v0.1.3
     #   with:
      #    host: ${{ secrets.SERVER_HOST }}
       #   username: ${{ secrets.SERVER_USER }}
       #   key: ${{ secrets.SERVER_SSH_KEY }}
        #  script: |
         #   docker pull luisfernandofernandes/geempe-api:${{ github.sha }}
          #  docker stop geempe-api || true
           # docker rm geempe-api || true
            #docker run -d --name geempe-api -p 80:80 luisfernandofernandes/geempe-api:${{ github.sha }}
